trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

variables:
  - group: log4j2-azure-blob-appender-vars
  - name: isGitHubTag
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]
  - name: COMPUTERNAME
    value: azuredevops
  - name: USERNAME
    value: azuredevopsuser

stages:
  - stage: Build
    jobs:
      - job: package
        condition: ne(variables['isGitHubTag'], 'true')
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
          - template: templates/prepare-maven.yml
          - task: Maven@3
            inputs:
              mavenPomFile: "pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.11"
              jdkArchitectureOption: "x64"
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              goals: "clean package verify"
              options: "--no-transfer-progress -DperformRelease=true -Dazure-pipelines=true -DaccountName=$(accountName) -DaccountKey=$(accountKey) -DcontainerName=$(containerName) -DsasUrl=$(sasUrl)"
          - script: |
              echo $(Build.SourcesDirectory)
              ls -al $(Build.SourcesDirectory)
              ls -al $(Build.SourcesDirectory)/target
              echo $(Build.ArtifactStagingDirectory)
              ls -al $(Build.ArtifactStagingDirectory)
  - stage: Publish
    dependsOn:
      - Build
    condition: and(succeeded(), eq(variables['isGitHubTag'], 'true'))
    jobs:
      - job: deploy
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
          - script: |
              VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
              echo $(VERSION_TAG)
          - template: templates/prepare-maven.yml
          - task: Maven@3
            inputs:
              mavenPomFile: "pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.11"
              jdkArchitectureOption: "x64"
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              goals: "clean deploy"
              options: "--no-transfer-progress -DperformRelease=true -DskipTests=true -Dchangelist= "
